# ccmake: Deroffing man parser
# Autogenerated from man pages
complete -c ccmake -s C --description 'Pre-load a script to populate the cache'
complete -c ccmake -s D --description 'Create a cmake cache entry'
complete -c ccmake -s U --description 'Remove matching entries from CMake cache'
complete -c ccmake -s G --description 'Specify a makefile generator'
complete -c ccmake -o Wno-dev --description 'Suppress developer warnings'
complete -c ccmake -o Wdev --description 'Enable developer warnings'

