# cpack: Deroffing man parser
# Autogenerated from man pages
complete -c cpack -s G --description 'Use the specified generator to generate packa... [See Man Page]'
complete -c cpack -s C --description 'Specify the project configuration  This optio... [See Man Page]'
complete -c cpack -s D --description 'Set a CPack variable'
complete -c cpack -l config --description 'Specify the config file'

