# gdbus-codegen: Deroffing man parser
# Autogenerated from man pages
complete -c gdbus-codegen -l interface-prefix --description 'A prefix to strip from all D-Bus interface na... [See Man Page]'
complete -c gdbus-codegen -l generate-docbook --description 'Generate Docbook Documentation for each D-Bus... [See Man Page]'
complete -c gdbus-codegen -l generate-c-code --description 'Generate C code for all D-Bus interfaces and ... [See Man Page]'
complete -c gdbus-codegen -l c-namespace --description 'The namespace to use for generated C code'
complete -c gdbus-codegen -l c-generate-object-manager --description 'If this option is passed, suitable #GDBusObje... [See Man Page]'
complete -c gdbus-codegen -l annotate --description 'Used to inject D-Bus annotations into the giv... [See Man Page]'
complete -c gdbus-codegen -l 'generate-c-code)'
complete -c gdbus-codegen -l 'generate-docbook).' --description 'GENERATING C CODE'
complete -c gdbus-codegen -o derived --description 'FooBar, two concrete instantiable types, FooB... [See Man Page]'

