# gdbus: Deroffing man parser
# Autogenerated from man pages
complete -c gdbus -l xml --description 'option is used, the returned introspection XM... [See Man Page]'
complete -c gdbus -l recurse --description 'option can be used to introspect children (an... [See Man Page]'
complete -c gdbus -l only-properties --description 'option can be used to only print the interfac... [See Man Page]'

