# git-stash: Deroffing man parser
# Autogenerated from man pages
complete -c git-stash -l 'include-untracked]' -l 'all]' --description 'Save your local modifications to a new stash,... [See Man Page]'
complete -c git-stash -l include-untracked --description 'option is used, all untracked files are also ... [See Man Page]'
complete -c git-stash -l all --description 'option is used instead then the ignored files... [See Man Page]'

