# git-format-patch: Deroffing man parser
# Autogenerated from man pages
complete -c git-format-patch -l minimal --description 'Spend extra time to make sure the smallest po... [See Man Page]'
complete -c git-format-patch -s W -l function-context --description 'Show whole surrounding functions of changes'
complete -c git-format-patch -l textconv -l no-textconv --description 'Allow (or disallow) external text conversion ... [See Man Page]'
complete -c git-format-patch -l stat-width
complete -c git-format-patch -l stat-name-width --description and
complete -c git-format-patch -l stat-count
complete -c git-format-patch -l no-to --description 'discards all To: headers added so far (from c... [See Man Page]'
complete -c git-format-patch -l no-cc --description 'discards all Cc: headers added so far (from c... [See Man Page]'
complete -c git-format-patch -l no-add-header --description 'discards all (To:, Cc:, and custom) headers a... [See Man Page]'

