# git-fast-export: Deroffing man parser
# Autogenerated from man pages
complete -c git-fast-export -l use-done-feature --description 'Start the stream with a feature done stanza, ... [See Man Page]'

