# git-submodule: Deroffing man parser
# Autogenerated from man pages
complete -c git-submodule -l init --description 'This option is only valid for the update comm... [See Man Page]'
complete -c git-submodule -l checkout --description 'to the command'
complete -c git-submodule -l 'cached)'
complete -c git-submodule -l submodule --description 'option with git-diff(1) will provide that inf... [See Man Page]'
complete -c git-submodule -l shared --description 'options carefully'

