# git-daemon: Deroffing man parser
# Autogenerated from man pages
complete -c git-daemon -l informative-errors -l no-informative-errors --description 'When informative errors are turned on, git-da... [See Man Page]'

