# git-diff-index: Deroffing man parser
# Autogenerated from man pages
complete -c git-diff-index -l minimal --description 'Spend extra time to make sure the smallest po... [See Man Page]'
complete -c git-diff-index -s W -l function-context --description 'Show whole surrounding functions of changes'
complete -c git-diff-index -l textconv -l no-textconv --description 'Allow (or disallow) external text conversion ... [See Man Page]'
complete -c git-diff-index -l stat-width
complete -c git-diff-index -l stat-name-width --description and
complete -c git-diff-index -l stat-count

