# git-tag: Deroffing man parser
# Autogenerated from man pages
complete -c git-tag -l annotate --description 'Make an unsigned, annotated tag object'
complete -c git-tag -l sign --description 'Make a GPG-signed tag, using the default e-ma... [See Man Page]'
complete -c git-tag -l local-user --description 'Make a GPG-signed tag, using the given key'
complete -c git-tag -l delete --description 'Delete existing tags with the given names'
complete -c git-tag -l verify --description 'Verify the gpg signature of the given tag nam... [See Man Page]'
complete -c git-tag -l list --description 'List tags with names that match the given pat... [See Man Page]'
complete -c git-tag -l message --description 'Use the given tag message (instead of prompti... [See Man Page]'
complete -c git-tag -l file --description 'Take the tag message from the given file'
complete -c git-tag -l cleanup --description 'This option sets how the tag message is clean... [See Man Page]'

