# git-log: Deroffing man parser
# Autogenerated from man pages
complete -c git-log -l minimal
complete -c git-log -l stat-width
complete -c git-log -l stat-name-width --description and
complete -c git-log -l stat-count
complete -c git-log -s W -l function-context
complete -c git-log -l textconv -l no-textconv

