# git-grep: Deroffing man parser
# Autogenerated from man pages
complete -c git-grep -l untracked --description 'In addition to searching in the tracked files... [See Man Page]'
complete -c git-grep -l no-exclude-standard --description 'Also search in ignored files by not honoring ... [See Man Page]'
complete -c git-grep -l exclude-standard --description 'Do not pay attention to ignored files specifi... [See Man Page]'
complete -c git-grep -l break --description 'Print an empty line between matches from diff... [See Man Page]'
complete -c git-grep -l heading --description 'Show the filename above the matches in that f... [See Man Page]'
complete -c git-grep -s C -l context --description 'Show <num> leading and trailing lines, and pl... [See Man Page]'
complete -c git-grep -s A -l after-context --description 'Show <num> trailing lines, and place a line c... [See Man Page]'
complete -c git-grep -s B -l before-context --description 'Show <num> leading lines, and place a line co... [See Man Page]'
complete -c git-grep -s W -l function-context --description 'Show the surrounding text from the previous l... [See Man Page]'
complete -c git-grep -l 'untracked.'
complete -c git-grep -l 'no-index.'

