# git-check-attr: Deroffing man parser
# Autogenerated from man pages
complete -c git-check-attr -s a -l all --description 'List all attributes that are associated with ... [See Man Page]'
complete -c git-check-attr -l cached --description 'Consider '

