# git-commit-tree: Deroffing man parser
# Autogenerated from man pages
complete -c git-commit-tree -s m --description 'A paragraph in the commig log message'
complete -c git-commit-tree -s F --description 'Read the commit log message from the given fi... [See Man Page]'

