# git-branch: Deroffing man parser
# Autogenerated from man pages
complete -c git-branch -l delete --description 'Delete a branch'
complete -c git-branch -l create-reflog --description 'Create the branch\\(cqs reflog'
complete -c git-branch -l move --description 'Move/rename a branch and the corresponding re... [See Man Page]'
complete -c git-branch -l remotes --description 'List or delete (if used with -d) the remote-t... [See Man Page]'
complete -c git-branch -l all --description 'List both remote-tracking branches and local ... [See Man Page]'
complete -c git-branch -l list --description 'Activate the list mode'
complete -c git-branch -l edit-description --description 'Open an editor and edit the text to explain w... [See Man Page]'

