# glib-compile-schemas: Deroffing man parser
# Autogenerated from man pages
complete -c glib-compile-schemas -s h -l help
complete -c glib-compile-schemas -l targetdir
complete -c glib-compile-schemas -l dry-run
complete -c glib-compile-schemas -l allow-any-name

