# glib-gettextize: Deroffing man parser
# Autogenerated from man pages
complete -c glib-gettextize -l no-changelog --description 'option)'
complete -c glib-gettextize -l help
complete -c glib-gettextize -l version
complete -c glib-gettextize -s c -l copy
complete -c glib-gettextize -s f -l force

