# glib-mkenums: Deroffing man parser
# Autogenerated from man pages
complete -c glib-mkenums -l fhead
complete -c glib-mkenums -l fprod
complete -c glib-mkenums -l ftail
complete -c glib-mkenums -l eprod
complete -c glib-mkenums -l vhead
complete -c glib-mkenums -l vprod
complete -c glib-mkenums -l vtail
complete -c glib-mkenums -l comments
complete -c glib-mkenums -l template
complete -c glib-mkenums -l help
complete -c glib-mkenums -l version

