# glib-genmarshal: Deroffing man parser
# Autogenerated from man pages
complete -c glib-genmarshal -l header
complete -c glib-genmarshal -l body
complete -c glib-genmarshal -l prefix -l prefix
complete -c glib-genmarshal -l skip-source
complete -c glib-genmarshal -l nostdinc
complete -c glib-genmarshal -l g-fatal-warnings
complete -c glib-genmarshal -s h -l help
complete -c glib-genmarshal -s v -l version

