# gobject-query: Deroffing man parser
# Autogenerated from man pages
complete -c gobject-query -s r
complete -c gobject-query -s n
complete -c gobject-query -s b
complete -c gobject-query -s i
complete -c gobject-query -s s
complete -c gobject-query -s h -l help
complete -c gobject-query -s v -l version

