# gtester: Deroffing man parser
# Autogenerated from man pages
complete -c gtester -s o --description 'option, gtester writes an XML report of the t... [See Man Page]'
complete -c gtester -s h -l help
complete -c gtester -s v -l version
complete -c gtester -l g-fatal-warnings
complete -c gtester -s k -l keep-going
complete -c gtester -s l
complete -c gtester -s m
complete -c gtester -s p
complete -c gtester -l seed
complete -c gtester -s q -l quiet
complete -c gtester -l verbose

