# mosh: Deroffing man parser
# Autogenerated from man pages
complete -c mosh -l client --description 'path to client helper on local machine (defau... [See Man Page]'
complete -c mosh -l server --description 'path to server helper on remote machine (defa... [See Man Page]'
complete -c mosh -l predict --description 'Controls use of speculative local echo'
complete -c mosh -s a --description 'Synonym for --predict=always'
complete -c mosh -s n --description 'Synonym for --predict=never'
complete -c mosh -s p -l port --description 'Use a particular server-side UDP port, for ex... [See Man Page]'

