# mosh-server: Deroffing man parser
# Autogenerated from man pages
complete -c mosh-server -s s --description 'bind to the local interface used for an incom... [See Man Page]'
complete -c mosh-server -s i --description 'IP address of the local interface to bind (fo... [See Man Page]'
complete -c mosh-server -s p --description 'UDP port number to bind'
complete -c mosh-server -s c --description 'Number of colors to advertise to applications... [See Man Page]'

